version: '3'
services:

  postgres_app:
    image: postgres:13
    container_name: app_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER_APP}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_APP}
      POSTGRES_DB: app
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER_APP}"]
      interval: 10s
      retries: 5

  postgres:
    image: postgres:13
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5

  webserver:
    image: apache/airflow:latest-python3.9
    container_name: airflow_webserver
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/airflow
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=true
      - SERVICE=webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./jobs:/fake_ecommerce_app/airflow/jobs
      - ./requirements.txt:/fake_ecommerce_app/requirements.txt
      - ./init.sh:/fake_ecommerce_app/init.sh
    ports:
      - "8080:8080"
    command: bash /fake_ecommerce_app/init.sh

  scheduler:
    image: apache/airflow:latest-python3.9
    container_name: airflow_scheduler
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/airflow
      - SERVICE=scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./jobs:/fake_ecommerce_app/airflow/jobs
      - ./requirements.txt:/fake_ecommerce_app/requirements.txt
      - ./init.sh:/fake_ecommerce_app/init.sh
    command: bash /fake_ecommerce_app/init.sh

volumes:
  postgres_data:
